apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: azure-voting-app
  name: azure-voting-app
spec:
  ports:
  - protocol: TCP
    targetPort: 11000
    nodePort: 30001
  selector:
    app: azure-voting-app
  type: NodePort
status:
  loadBalancer: {}